/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
  // Note: font optimization was intentionally left alone; font shims are used when
  // an autogenerated font loader reference is present to avoid runtime errors.
}

export default nextConfig
