"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Download, Edit2, Copy, Check, RefreshCw, BookOpen } from "lucide-react"

interface StoryDisplayProps {
  story: any
  onUpdate: (story: any) => void
}

export function StoryDisplay({ story, onUpdate }: StoryDisplayProps) {
  const [isEditing, setIsEditing] = useState(false)
  const [editedPlot, setEditedPlot] = useState(story.plot)
  const [copied, setCopied] = useState(false)
  const [wordCount, setWordCount] = useState(0)

  // Calculate word count
  const calculateWordCount = (text: string) => {
    return text.trim().split(/\s+/).length
  }

  // Update word count when plot changes
  const handlePlotChange = (value: string) => {
    setEditedPlot(value)
    setWordCount(calculateWordCount(value))
  }

  const handleSave = () => {
    onUpdate({ ...story, plot: editedPlot, updatedAt: new Date() })
    setIsEditing(false)
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(editedPlot)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExport = () => {
    const exportDate = new Date().toLocaleString()
    const content = `
================================================================================
                          STORY PLOT GENERATOR - EXPORT
================================================================================

STORY DETAILS
─────────────────────────────────────────────────────────────────────────────
Genre: ${story.genre}
${story.characters ? `Characters: ${story.characters}` : ""}
Theme: ${story.prompt}
Created: ${new Date(story.createdAt).toLocaleString()}
Word Count: ${wordCount}

================================================================================
                                   PLOT
================================================================================

${editedPlot}

================================================================================
                              END OF STORY PLOT
================================================================================
Generated by AI Story Plot Generator
${new Date().toLocaleString()}
    `.trim()

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.setAttribute("href", url)
    link.setAttribute("download", `story-${story.genre.toLowerCase()}-${Date.now()}.txt`)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const handleExportJSON = () => {
    const jsonData = {
      type: "Story Plot",
      genre: story.genre,
      characters: story.characters || "Auto-generated",
      theme: story.prompt,
      plot: editedPlot,
      metadata: {
        createdAt: story.createdAt,
        updatedAt: story.updatedAt || story.createdAt,
        wordCount: wordCount,
      },
    }

    const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: "application/json" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.setAttribute("href", url)
    link.setAttribute("download", `story-${Date.now()}.json`)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const handleRegenerate = () => {
    // This would trigger regeneration - parent component should handle
    window.scrollTo({ top: 0, behavior: "smooth" })
  }

  return (
    <div className="space-y-6 animate-fade-in-up">
      {/* Story Metadata Card */}
      <Card className="p-6 border border-border">
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-accent/10 rounded-lg">
              <BookOpen className="w-5 h-5 text-accent" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-foreground">Story Information</h3>
              <p className="text-sm text-muted-foreground">Plot details and metadata</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
          <div className="p-4 rounded-lg bg-secondary/30 border border-border">
            <p className="text-xs font-semibold text-muted-foreground uppercase">Genre</p>
            <p className="font-bold text-foreground mt-1">{story.genre}</p>
          </div>
          <div className="p-4 rounded-lg bg-secondary/30 border border-border">
            <p className="text-xs font-semibold text-muted-foreground uppercase">Created</p>
            <p className="font-bold text-foreground mt-1">{new Date(story.createdAt).toLocaleDateString()}</p>
          </div>
          {story.characters && (
            <div className="p-4 rounded-lg bg-secondary/30 border border-border sm:col-span-2">
              <p className="text-xs font-semibold text-muted-foreground uppercase">Characters</p>
              <p className="font-bold text-foreground mt-1 line-clamp-2">{story.characters}</p>
            </div>
          )}
          <div className="p-4 rounded-lg bg-secondary/30 border border-border">
            <p className="text-xs font-semibold text-muted-foreground uppercase">Word Count</p>
            <p className="font-bold text-foreground mt-1">{wordCount} words</p>
          </div>
          <div className="p-4 rounded-lg bg-secondary/30 border border-border">
            <p className="text-xs font-semibold text-muted-foreground uppercase">Theme</p>
            <p className="font-bold text-foreground mt-1 line-clamp-2">{story.prompt}</p>
          </div>
        </div>
      </Card>

      {/* Story Plot Card */}
      <Card className="p-6 border border-border">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="text-lg font-bold text-foreground">Plot</h3>
            <p className="text-sm text-muted-foreground">Generated story narrative</p>
          </div>
          <div className="flex gap-2 flex-wrap justify-end">
            <Button
              size="sm"
              variant="outline"
              onClick={handleCopy}
              className="border-border text-foreground hover:bg-secondary bg-transparent"
              title="Copy to clipboard"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 mr-1" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 mr-1" />
                  Copy
                </>
              )}
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={handleExport}
              className="border-border text-foreground hover:bg-secondary bg-transparent"
              title="Export as text"
            >
              <Download className="w-4 h-4 mr-1" />
              TXT
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={handleExportJSON}
              className="border-border text-foreground hover:bg-secondary bg-transparent"
              title="Export as JSON"
            >
              <Download className="w-4 h-4 mr-1" />
              JSON
            </Button>
            <Button
              size="sm"
              onClick={() => setIsEditing(!isEditing)}
              className="bg-accent hover:bg-accent/90 text-accent-foreground"
            >
              <Edit2 className="w-4 h-4 mr-1" />
              {isEditing ? "Cancel" : "Edit"}
            </Button>
          </div>
        </div>

        {isEditing ? (
          <div className="space-y-4">
            <textarea
              value={editedPlot}
              onChange={(e) => handlePlotChange(e.target.value)}
              rows={15}
              className="w-full px-4 py-3 bg-input border border-border rounded-lg text-foreground placeholder-muted-foreground focus:outline-none focus:ring-2 focus:ring-accent resize-none font-mono text-sm"
            />
            <div className="flex items-center justify-between">
              <p className="text-xs text-muted-foreground">{editedPlot.length} characters</p>
              <div className="flex gap-3 justify-end">
                <Button
                  variant="outline"
                  onClick={() => {
                    setIsEditing(false)
                    setEditedPlot(story.plot)
                  }}
                  className="border-border text-foreground hover:bg-secondary"
                >
                  Cancel
                </Button>
                <Button onClick={handleSave} className="bg-primary hover:bg-primary/90 text-primary-foreground">
                  Save Changes
                </Button>
              </div>
            </div>
          </div>
        ) : (
          <div className="prose prose-sm max-w-none dark:prose-invert">
            <div className="bg-card/50 p-6 rounded-lg border border-border/50 text-foreground whitespace-pre-wrap leading-relaxed font-medium">
              {editedPlot}
            </div>
          </div>
        )}
      </Card>

      {/* Action Cards */}
      <Card className="p-6 border border-border bg-gradient-to-r from-primary/5 to-accent/5">
        <p className="text-sm text-muted-foreground mb-4">Want to create another story?</p>
        <Button
          onClick={handleRegenerate}
          className="bg-gradient-to-r from-primary to-accent hover:opacity-90 text-primary-foreground w-full sm:w-auto"
        >
          <RefreshCw className="w-4 h-4 mr-2" />
          Generate New Story
        </Button>
      </Card>
    </div>
  )
}
