// Define noop shims for any autogenerated font loader calls (e.g. Geist)
// This prevents runtime ReferenceError if a font loader is referenced but the
// import is missing or stripped by optimization.
declare const globalThis: any;
if (typeof globalThis.Geist === "undefined") {
  globalThis.Geist = function () {
    return { className: "" };
  };
}
if (typeof globalThis.Geist_Mono === "undefined") {
  globalThis.Geist_Mono = function () {
    return { className: "" };
  };
}

export {};
